name: 'Publish files'
description: 'Publish files via artifacts and SSH'
author: 'Fabien Ors'

inputs:
  host:
    description: 'Server where you can execute SSH commands'
  username:
    description: 'Username for SSH connection'
  password:
    description: 'Password for SSH connection'
  dest-path:
    description: 'Full path to the destination folder in the server'
    default: "~"
  pattern:
    description: 'File name pattern filter'
    default: "*"
    
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      # Downloading several artifacts:
      # https://github.com/actions/download-artifact/issues/103#issuecomment-1290368250
      with:
        path: download_artifacts
    
    - name: Retrieve the list of files (all artifacts)
      # For join_by function: https://stackoverflow.com/a/17841619/3952924
      run: |
        ls -ls download_artifacts/*/${{ inputs.pattern }}
        flist=$(ls download_artifacts/*/${{ inputs.pattern }})
        function join_by { local IFS="$1"; shift; echo "$*"; }
        fflist=$(join_by , $flist)
        echo "Artifacts retrieved: $fflist"
        echo "FILE_LIST=$fflist" >> "$GITHUB_ENV"
        fflist=$(join_by ' ' $flist)
        echo "Artifacts retrieved (2): $fflist"
        echo "FILE_LIST2=$fflist" >> "$GITHUB_ENV"
      shell: bash
      
    - name: Upload all packages to the server
      uses: appleboy/scp-action@master
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        source: ${{ env.FILE_LIST }}
        target: ~/

    - name: Move each file to destination and remove download_artifacts folder
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        script: for f in ${{ env.FILE_LIST2 }}; do mv $f ${{ inputs.dest-path }}; done; rm -rf ~/download_artifacts

